spring:
  application:
    name: user-service #current service name to be used by the eureka server
    
eureka:  instance:    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    
  client:    service-url:      default-zone: http://localhost:8761/eureka/
    healthcheck:      enabled: true        